### ISSUE TITLE
Allow nnef_tools pip install from git

### ISSUE THREAD

**Issue by idenc** [KhronosGroup/NNEF-Tools#106]
Allowing to install nnef_tools package with the command ```pip install git+https://github.com/KhronosGroup/NNEF-Tools.git``` would be very convenient. +

Currently I get this error:
```
(venv) >pip install git+https://github.com/KhronosGroup/NNEF-Tools.git
Collecting git+https://github.com/KhronosGroup/NNEF-Tools.git
  Cloning https://github.com/KhronosGroup/NNEF-Tools.git to c:\users\iden\appdata\local\temp\pip-req-build-s_8ugsgs
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info\nnef_tools.egg-info
    writing pip-egg-info\nnef_tools.egg-info\PKG-INFO
    writing dependency_links to pip-egg-info\nnef_tools.egg-info\dependency_links.txt
    writing top-level names to pip-egg-info\nnef_tools.egg-info\top_level.txt
    writing manifest file 'pip-egg-info\nnef_tools.egg-info\SOURCES.txt'
    reading manifest file 'pip-egg-info\nnef_tools.egg-info\SOURCES.txt'
    writing manifest file 'pip-egg-info\nnef_tools.egg-info\SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\iden\AppData\Local\Temp\pip-req-build-s_8ugsgs\setup.py", line 38, in <module>
        shutil.rmtree('build')
      File "C:\Users\Iden\AppData\Local\Programs\Python\Python36\lib\shutil.py", line 500, in rmtree
        return _rmtree_unsafe(path, onerror)
      File "C:\Users\Iden\AppData\Local\Programs\Python\Python36\lib\shutil.py", line 382, in _rmtree_unsafe
        onerror(os.listdir, path, sys.exc_info())
      File "C:\Users\Iden\AppData\Local\Programs\Python\Python36\lib\shutil.py", line 380, in _rmtree_unsafe
        names = os.listdir(path)
    FileNotFoundError: [WinError 3] The system cannot find the path specified: 'build'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\iden\AppData\Local\Temp\pip-req-build-s_8ugsgs\
```
Which looks like the shutils.rmtree is failing. If you guys could take a look at this I would appreciate it.

**Comment by gyenesvi** [comment]
I have posted an update, can you try again now?

**Comment by idenc** [comment]
Awesome, it works now. Thanks!
