### ISSUE TITLE
NNEF optimizer fails with KeyError

### ISSUE THREAD

**Issue by dvorotnev** [KhronosGroup/NNEF-Tools#143]
I am trying to save and to convert the [Emotion FerPlus network](https://github.com/onnx/models/tree/master/vision/body_analysis/emotion_ferplus) from ONNX to NNEF with `--optimize` flag using the following commands:
```
wget https://github.com/onnx/models/raw/master/vision/body_analysis/emotion_ferplus/model/emotion-ferplus-8.tar.gz
tar -xf emotion-ferplus-8.tar.gz
python -m nnef_tools.convert --input-format=onnx --output-format=nnef --optimize --input-model=emotion_ferplus/model.onnx --output-model=./model.nnef
```
But the optimizer fails with this error:
```
Traceback (most recent call last):
  File "/nix/store/xkvjcsv75k1z7yjdwglz423wfl8biv0p-python3-3.7.9/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/nix/store/xkvjcsv75k1z7yjdwglz423wfl8biv0p-python3-3.7.9/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/nix/store/c7rf7k3264gxx4kfcp3qqzdvhgn9g9rg-python3.7-nnef-tools-python-0.3/lib/python3.7/site-packages/nnef_tools/convert.py", line 338, in <module>
    exit(main(parser.parse_args()))
  File "/nix/store/c7rf7k3264gxx4kfcp3qqzdvhgn9g9rg-python3.7-nnef-tools-python-0.3/lib/python3.7/site-packages/nnef_tools/convert.py", line 285, in main
    graph = optimizer(graph)
  File "/nix/store/c7rf7k3264gxx4kfcp3qqzdvhgn9g9rg-python3.7-nnef-tools-python-0.3/lib/python3.7/site-packages/nnef_tools/optimization/nnef_optimizer.py", line 66, in __call__
    changed |= replace_chain(graph, ['matmul', {'add', 'sub'}], self._merge_matmul_bias)
  File "/nix/store/c7rf7k3264gxx4kfcp3qqzdvhgn9g9rg-python3.7-nnef-tools-python-0.3/lib/python3.7/site-packages/nnef_tools/model/utils.py", line 115, in replace_chain
    if chain is not None and func(*chain) is not False:
  File "/nix/store/c7rf7k3264gxx4kfcp3qqzdvhgn9g9rg-python3.7-nnef-tools-python-0.3/lib/python3.7/site-packages/nnef_tools/optimization/nnef_optimizer.py", line 192, in _merge_matmul_bias
    if matmul.attribs['transposeA']:
KeyError: 'transposeA'
```
I have created a pull request with bug fix, but I am not sure that it is right.

**Comment by gyenesvi** [comment]
I have added a fix, can you retry?

**Comment by dvorotnev** [comment]
Now it works. Thanks!
