### ISSUE TITLE
Caffe To NNEF

### ISSUE THREAD

**Issue by wglee92** [KhronosGroup/NNEF-Tools#16]
Hi,
after training LeNet on MNIST, I am trying to convert this.
But I got following error.
(Is ppc64 the cause of the problem?)
Please let me know

```
root@0f5cd447d8e7:/opt/DL/caffe-ibm/NNEF-Tools/converter/caffe/src# python export_nnef_description.py --graph /opt/DL/caffe-ibm/examples/mnist/lenet_train_test.prototxt
not_gpu
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0410 01:47:14.810286  4627 _caffe.cpp:139] DEPRECATION WARNING - deprecated use of Python interface
W0410 01:47:14.810350  4627 _caffe.cpp:140] Use this instead (with the named "weights" parameter):
W0410 01:47:14.810360  4627 _caffe.cpp:142] Net('/opt/DL/caffe-ibm/examples/mnist/lenet_train_test.prototxt', 1, weights='/opt/DL/caffe-ibm/examples/mnist/lenet_train_test.caffemodel')
I0410 01:47:14.812103  4627 net.cpp:523] The NetState phase (1) differed from the phase (0) specified by a rule in layer mnist
I0410 01:47:14.812125  4627 net.cpp:57] Initializing net from parameters:
name: "LeNet"
state {
  phase: TEST
  level: 0
}
layer {
  name: "mnist"
  type: "Data"
  top: "data"
  top: "label"
  include {
    phase: TEST
  }
  transform_param {
    scale: 0.00390625
  }
  data_param {
    source: "/opt/DL/caffe-ibm/examples/mnist/mnist_test_lmdb"
    batch_size: 100
    backend: LMDB
  }
}
layer {
  name: "conv1"
  type: "Convolution"
  bottom: "data"
  top: "conv1"
  param {
    lr_mult: 1
  }
  param {
    lr_mult: 2
  }
  convolution_param {
    num_output: 20
    kernel_size: 5
    stride: 1
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
    }
  }
}
layer {
  name: "pool1"
  type: "Pooling"
  bottom: "conv1"
  top: "pool1"
  pooling_param {
    pool: MAX
    kernel_size: 2
    stride: 2
  }
}
layer {
  name: "conv2"
  type: "Convolution"
  bottom: "pool1"
  top: "conv2"
  param {
    lr_mult: 1
  }
  param {
    lr_mult: 2
  }
  convolution_param {
    num_output: 50
    kernel_size: 5
    stride: 1
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
    }
  }
}
layer {
  name: "pool2"
  type: "Pooling"
  bottom: "conv2"
  top: "pool2"
  pooling_param {
    pool: MAX
    kernel_size: 2
    stride: 2
  }
}
layer {
  name: "ip1"
  type: "InnerProduct"
  bottom: "pool2"
  top: "ip1"
  param {
    lr_mult: 1
  }
  param {
    lr_mult: 2
  }
  inner_product_param {
    num_output: 500
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
    }
  }
}
layer {
  name: "relu1"
  type: "ReLU"
  bottom: "ip1"
  top: "ip1"
}
layer {
  name: "ip2"
  type: "InnerProduct"
  bottom: "ip1"
  top: "ip2"
  param {
    lr_mult: 1
  }
  param {
    lr_mult: 2
  }
  inner_product_param {
    num_output: 10
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
    }
  }
}
layer {
  name: "accuracy"
  type: "Accuracy"
  bottom: "ip2"
  bottom: "label"
  top: "accuracy"
  include {
    phase: TEST
  }
}
layer {
  name: "loss"
  type: "SoftmaxWithLoss"
  bottom: "ip2"
  bottom: "label"
  top: "loss"
}
I0410 01:47:14.812471  4627 layer_factory.hpp:77] Creating layer mnist
I0410 01:47:14.812582  4627 db_lmdb.cpp:35] Opened lmdb /opt/DL/caffe-ibm/examples/mnist/mnist_test_lmdb
I0410 01:47:14.812618  4627 net.cpp:90] Creating Layer mnist
I0410 01:47:14.812631  4627 net.cpp:609] mnist -> data
I0410 01:47:14.812661  4627 net.cpp:609] mnist -> label
I0410 01:47:14.831743  4627 data_layer.cpp:50] output data size: 100,1,28,28
I0410 01:47:14.834853  4627 net.cpp:128] Setting up mnist
I0410 01:47:14.834867  4627 net.cpp:135] Top shape: 100 1 28 28 (78400)
I0410 01:47:14.834884  4627 net.cpp:135] Top shape: 100 (100)
I0410 01:47:14.834894  4627 net.cpp:143] Memory required for data: 314000
I0410 01:47:14.834905  4627 layer_factory.hpp:77] Creating layer label_mnist_1_split
I0410 01:47:14.834923  4627 net.cpp:90] Creating Layer label_mnist_1_split
I0410 01:47:14.834933  4627 net.cpp:635] label_mnist_1_split <- label
I0410 01:47:14.834949  4627 net.cpp:609] label_mnist_1_split -> label_mnist_1_split_0
I0410 01:47:14.834965  4627 net.cpp:609] label_mnist_1_split -> label_mnist_1_split_1
I0410 01:47:14.834982  4627 net.cpp:128] Setting up label_mnist_1_split
I0410 01:47:14.834990  4627 net.cpp:135] Top shape: 100 (100)
I0410 01:47:14.835000  4627 net.cpp:135] Top shape: 100 (100)
I0410 01:47:14.835008  4627 net.cpp:143] Memory required for data: 314800
I0410 01:47:14.835016  4627 layer_factory.hpp:77] Creating layer conv1
I0410 01:47:14.835036  4627 net.cpp:90] Creating Layer conv1
I0410 01:47:14.835042  4627 net.cpp:635] conv1 <- data
I0410 01:47:14.835053  4627 net.cpp:609] conv1 -> conv1
I0410 01:47:15.208873  4627 net.cpp:128] Setting up conv1
I0410 01:47:15.208895  4627 net.cpp:135] Top shape: 100 20 24 24 (1152000)
I0410 01:47:15.208909  4627 net.cpp:143] Memory required for data: 4922800
I0410 01:47:15.208935  4627 layer_factory.hpp:77] Creating layer pool1
I0410 01:47:15.208950  4627 net.cpp:90] Creating Layer pool1
I0410 01:47:15.208957  4627 net.cpp:635] pool1 <- conv1
I0410 01:47:15.208968  4627 net.cpp:609] pool1 -> pool1
I0410 01:47:15.208992  4627 net.cpp:128] Setting up pool1
I0410 01:47:15.208999  4627 net.cpp:135] Top shape: 100 20 12 12 (288000)
I0410 01:47:15.209009  4627 net.cpp:143] Memory required for data: 6074800
I0410 01:47:15.209017  4627 layer_factory.hpp:77] Creating layer conv2
I0410 01:47:15.209033  4627 net.cpp:90] Creating Layer conv2
I0410 01:47:15.209041  4627 net.cpp:635] conv2 <- pool1
I0410 01:47:15.209051  4627 net.cpp:609] conv2 -> conv2
I0410 01:47:15.210180  4627 net.cpp:128] Setting up conv2
I0410 01:47:15.210191  4627 net.cpp:135] Top shape: 100 50 8 8 (320000)
I0410 01:47:15.210203  4627 net.cpp:143] Memory required for data: 7354800
I0410 01:47:15.210217  4627 layer_factory.hpp:77] Creating layer pool2
I0410 01:47:15.210227  4627 net.cpp:90] Creating Layer pool2
I0410 01:47:15.210235  4627 net.cpp:635] pool2 <- conv2
I0410 01:47:15.210245  4627 net.cpp:609] pool2 -> pool2
I0410 01:47:15.210258  4627 net.cpp:128] Setting up pool2
I0410 01:47:15.210266  4627 net.cpp:135] Top shape: 100 50 4 4 (80000)
I0410 01:47:15.210276  4627 net.cpp:143] Memory required for data: 7674800
I0410 01:47:15.210284  4627 layer_factory.hpp:77] Creating layer ip1
I0410 01:47:15.210299  4627 net.cpp:90] Creating Layer ip1
I0410 01:47:15.210306  4627 net.cpp:635] ip1 <- pool2
I0410 01:47:15.210317  4627 net.cpp:609] ip1 -> ip1
I0410 01:47:15.212950  4627 net.cpp:128] Setting up ip1
I0410 01:47:15.212960  4627 net.cpp:135] Top shape: 100 500 (50000)
I0410 01:47:15.212970  4627 net.cpp:143] Memory required for data: 7874800
I0410 01:47:15.212982  4627 layer_factory.hpp:77] Creating layer relu1
I0410 01:47:15.212991  4627 net.cpp:90] Creating Layer relu1
I0410 01:47:15.212999  4627 net.cpp:635] relu1 <- ip1
I0410 01:47:15.213008  4627 net.cpp:596] relu1 -> ip1 (in-place)
I0410 01:47:15.213516  4627 net.cpp:128] Setting up relu1
I0410 01:47:15.213526  4627 net.cpp:135] Top shape: 100 500 (50000)
I0410 01:47:15.213536  4627 net.cpp:143] Memory required for data: 8074800
I0410 01:47:15.213542  4627 layer_factory.hpp:77] Creating layer ip2
I0410 01:47:15.213555  4627 net.cpp:90] Creating Layer ip2
I0410 01:47:15.213563  4627 net.cpp:635] ip2 <- ip1
I0410 01:47:15.213573  4627 net.cpp:609] ip2 -> ip2
I0410 01:47:15.213624  4627 net.cpp:128] Setting up ip2
I0410 01:47:15.213632  4627 net.cpp:135] Top shape: 100 10 (1000)
I0410 01:47:15.213641  4627 net.cpp:143] Memory required for data: 8078800
I0410 01:47:15.213651  4627 layer_factory.hpp:77] Creating layer ip2_ip2_0_split
I0410 01:47:15.213661  4627 net.cpp:90] Creating Layer ip2_ip2_0_split
I0410 01:47:15.213668  4627 net.cpp:635] ip2_ip2_0_split <- ip2
I0410 01:47:15.213677  4627 net.cpp:609] ip2_ip2_0_split -> ip2_ip2_0_split_0
I0410 01:47:15.213688  4627 net.cpp:609] ip2_ip2_0_split -> ip2_ip2_0_split_1
I0410 01:47:15.213701  4627 net.cpp:128] Setting up ip2_ip2_0_split
I0410 01:47:15.213708  4627 net.cpp:135] Top shape: 100 10 (1000)
I0410 01:47:15.213716  4627 net.cpp:135] Top shape: 100 10 (1000)
I0410 01:47:15.213726  4627 net.cpp:143] Memory required for data: 8086800
I0410 01:47:15.213732  4627 layer_factory.hpp:77] Creating layer accuracy
I0410 01:47:15.213747  4627 net.cpp:90] Creating Layer accuracy
I0410 01:47:15.213753  4627 net.cpp:635] accuracy <- ip2_ip2_0_split_0
I0410 01:47:15.213762  4627 net.cpp:635] accuracy <- label_mnist_1_split_0
I0410 01:47:15.213773  4627 net.cpp:609] accuracy -> accuracy
I0410 01:47:15.213788  4627 net.cpp:128] Setting up accuracy
I0410 01:47:15.213796  4627 net.cpp:135] Top shape: (1)
I0410 01:47:15.213805  4627 net.cpp:143] Memory required for data: 8086804
I0410 01:47:15.213814  4627 layer_factory.hpp:77] Creating layer loss
I0410 01:47:15.213824  4627 net.cpp:90] Creating Layer loss
I0410 01:47:15.213832  4627 net.cpp:635] loss <- ip2_ip2_0_split_1
I0410 01:47:15.213840  4627 net.cpp:635] loss <- label_mnist_1_split_1
I0410 01:47:15.213850  4627 net.cpp:609] loss -> loss
I0410 01:47:15.213866  4627 layer_factory.hpp:77] Creating layer loss
I0410 01:47:15.214092  4627 net.cpp:128] Setting up loss
I0410 01:47:15.214100  4627 net.cpp:135] Top shape: (1)
I0410 01:47:15.214110  4627 net.cpp:138]     with loss weight 1
I0410 01:47:15.214130  4627 net.cpp:143] Memory required for data: 8086808
I0410 01:47:15.214138  4627 net.cpp:204] loss needs backward computation.
I0410 01:47:15.214146  4627 net.cpp:206] accuracy does not need backward computation.
I0410 01:47:15.214155  4627 net.cpp:204] ip2_ip2_0_split needs backward computation.
I0410 01:47:15.214164  4627 net.cpp:204] ip2 needs backward computation.
I0410 01:47:15.214171  4627 net.cpp:204] relu1 needs backward computation.
I0410 01:47:15.214179  4627 net.cpp:204] ip1 needs backward computation.
I0410 01:47:15.214187  4627 net.cpp:204] pool2 needs backward computation.
I0410 01:47:15.214195  4627 net.cpp:204] conv2 needs backward computation.
I0410 01:47:15.214203  4627 net.cpp:204] pool1 needs backward computation.
I0410 01:47:15.214211  4627 net.cpp:204] conv1 needs backward computation.
I0410 01:47:15.214221  4627 net.cpp:206] label_mnist_1_split does not need backward computation.
I0410 01:47:15.214228  4627 net.cpp:206] mnist does not need backward computation.
I0410 01:47:15.214236  4627 net.cpp:248] This network produces output accuracy
I0410 01:47:15.214244  4627 net.cpp:248] This network produces output loss
I0410 01:47:15.214259  4627 net.cpp:261] Network initialization done.
I0410 01:47:15.214270  4627 net.cpp:284] Caffe summary was disabled
Traceback (most recent call last):
  File "./export_nnef_description.py", line 47, in <module>
    net = buildNet(p,w,deconv_as_resamp=True)
  File "/opt/DL/caffe-ibm/NNEF-Tools/converter/caffe/src/export_from_caffe.py", line 412, in buildNet
    tmpfile.name])
  File "/usr/lib/python2.7/subprocess.py", line 536, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

```

**Comment by garaczit** [comment]
Hi,

it seems the converter fails to find an executable file named upgrade_net_proto_text.bin in the caffe build folder. Please check the following:

- "CAFFE_BIN_FOLDER" environment variable needs to be set to the path of your caffe/build/tools folder (so that the converter will know where to find the executable)
- Caffe needs to be successfully built (so that the executable will be present in that folder)

**Comment by gyenesvi** [comment]
@wglee92, any feedback on this? Does the above fix your problem?
