### ISSUE TITLE
How to export weights in TF -> NNEF converter.

### ISSUE THREAD

**Issue by lcskrishna** [KhronosGroup/NNEF-Tools#19]
I am trying out the example given in converter/tensorflow/sample_export.py

I was able to run the example given. 
Also, I want to know is there any way that I can export the weights similar to the converter in caffe?

Note: I tried modifying checkpoint= None to checkpoint = "resnet50", I got the following error:

```
% python sample_export.py

Tracing invocations... done
Tracing dependencies... done
Traceback (most recent call last):
  File "sample_export.py", line 41, in <module>
    converter = tf2nnef.export_network(network, checkpoint)
  File "NNEF-Tools/converter/tensorflow/src/tf2nnef.py", line 1335, in export_network
    reader = tf.contrib.framework.load_checkpoint(checkpoint) if checkpoint is not None else None
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/framework/python/framework/checkpoint_utils.py", line 63, in load_checkpoint
    return train.NewCheckpointReader(filename)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 110, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern), status)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for resnet50

```

Appreciate any kind of help to export the weights.

Thanks.

**Comment by lcskrishna** [comment]
@gyenesvi 
Thanks for the quick reply. It works.
