### ISSUE TITLE
Error converting caffe model to NNEF

### ISSUE THREAD

**Issue by syedaffanhamdani** [KhronosGroup/NNEF-Tools#65]
Hello, the shell script in the caffe converter examples folder is failing with the following error. 
I then used ResNet50 Model along with the model file but error remains the same.
Can you please guide what could be the issue?
Thanks

Command that I used : caffe_to_nnef -m ResNet-50-model.caffemodel ResNet-50-deplo
y.prototxt -o converted_to_nnef

```
Traceback (most recent call last):
  File "/usr/local/bin/caffe_to_nnef", line 11, in <module>
    load_entry_point('nnef-converters==0.1.0', 'console_scripts', 'caffe_to_nnef')()
  File "/usr/local/lib/python2.7/dist-packages/nnef_converters-0.1.0-py2.7.egg/nnef_converters/caffe_converters/caffe_to_nnef/command.py", line 102, in main
    verbose=args.verbose)
  File "/usr/local/lib/python2.7/dist-packages/nnef_converters-0.1.0-py2.7.egg/nnef_converters/caffe_converters/caffe_to_nnef/caffe_to_nnef.py", line 107, in convert
    with_variables=caffemodel_path is not None)
  File "/usr/local/lib/python2.7/dist-packages/nnef_converters-0.1.0-py2.7.egg/nnef_converters/caffe_converters/caffe_to_nnef/caffe_to_nnef.py", line 52, in prototxt_to_nnef
    with_variables=with_variables)
  File "/usr/local/lib/python2.7/dist-packages/nnef_converters-0.1.0-py2.7.egg/nnef_converters/caffe_converters/caffe_to_nnef/caffe_to_dog/caffe_to_dog.py", line 79, in prototxt_to_caffedog
    subprocess.check_call([upgrade_bin, prototxt_file_name, tmp_file.name])
  File "/usr/lib/python2.7/subprocess.py", line 536, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by gyenesvi** [comment]
Well, it says it can't find some file, presumably the input file, so make sure you are giving the right path. Note that you might have to give it full path, or call python from the folder where the model is. Did you try these?

**Comment by gyenesvi** [comment]
In fact, we have realized that the problem may be that the converter tries to run an upgrade script inside Caffe, and it might not find that script. We have submitted a fix, can you try it now?

**Comment by syedaffanhamdani** [comment]
Thanks for the response. I pulled the latest fix and tried using only the example shelll script provided in the
```
NNEF-Tools/converter/nnef_converters/caffe_converters/examples/
``` 
Problem remains the same. Here are the logs although they are just same. Shell script: " ./convert_to_nnef.sh"

```
Creating dummy model

Small test (with model)
Traceback (most recent call last):
  File "/usr/local/bin/caffe_to_nnef", line 11, in <module>
    load_entry_point('nnef-converters==0.1.0', 'console_scripts', 'caffe_to_nnef')()
  File "/usr/local/lib/python2.7/dist-packages/nnef_converters-0.1.0-py2.7.egg/nnef_converters/caffe_converters/caffe_to_nnef/command.py", line 102, in main
    verbose=args.verbose)
  File "/usr/local/lib/python2.7/dist-packages/nnef_converters-0.1.0-py2.7.egg/nnef_converters/caffe_converters/caffe_to_nnef/caffe_to_nnef.py", line 107, in convert
    with_variables=caffemodel_path is not None)
  File "/usr/local/lib/python2.7/dist-packages/nnef_converters-0.1.0-py2.7.egg/nnef_converters/caffe_converters/caffe_to_nnef/caffe_to_nnef.py", line 52, in prototxt_to_nnef
    with_variables=with_variables)
  File "/usr/local/lib/python2.7/dist-packages/nnef_converters-0.1.0-py2.7.egg/nnef_converters/caffe_converters/caffe_to_nnef/caffe_to_dog/caffe_to_dog.py", line 79, in prototxt_to_caffedog
    subprocess.check_call([upgrade_bin, prototxt_file_name, tmp_file.name])
  File "/usr/lib/python2.7/subprocess.py", line 536, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
Can you please guide what does **py2.7.egg/nnef_converters/caffe_converters/caffe_to_nnef/caffe_to_nnef.py", line 107, in convert
    with_variables=caffemodel_path is not None)** mean?

**Comment by gyenesvi** [comment]
If you have the latest code, it should not give this error message, but a different one. Did you rerun the installation after pulling the latest code?

```
cd nnef_converters
python setup.py install
```

You might still be running the cached old version.

The line that you ask above is irrelevant for this, but it means that if a caffemodel (weights) is given, those are also converted, otherwise only the graph.

**Comment by syedaffanhamdani** [comment]
A bundle of thanks. Worked perfectly after re-running the installation.
