### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by jo7ueb** [KhronosGroup/NNEF-Tools#9]
When I tried to use Caffe To NNEF converter, I got following error.

```
root@91b3c88b45be:/nnef/converter/caffe/src# python3 export_nnef_description.py --graph /yendo/codes/tech-research/nnframework/onnx/in/caffenet/predict_net.pb
Traceback (most recent call last):
  File "export_nnef_description.py", line 16, in <module>
    from nnef_format import *
  File "/nnef/converter/caffe/src/nnef_format.py", line 16, in <module>
    from export_from_caffe import *
  File "/nnef/converter/caffe/src/export_from_caffe.py", line 18, in <module>
    from abstractnet import *
  File "/nnef/converter/caffe/src/abstractnet.py", line 19
    print s
          ^
SyntaxError: Missing parentheses in call to 'print'
```

Syntax for `print` has been changed in Python 3.
I think new project like NNEF should support Python 3.

**Comment by gyenesvi** [comment]
Thanks, seems like an easy fix, will let you know when it's done.

**Comment by gyenesvi** [comment]
This should be working now, @jo7ueb can you try it?
